<a href="https://colab.research.google.com/github/eric-sun92/tensorflow_tensor_fundamentals/blob/main/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

In [4]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
scalar.ndim, scalar.shape

(0, TensorShape([]))

In [6]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
matrix = tf.constant([[10, 7],
                      [7, 10]], dtype=tf.float16)
matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[10.,  7.],
        [ 7., 10.]], dtype=float16)>,
 2)

Changeable (tf.Variable) vs Non-changeable (tf.constant) Tensors

In [9]:
changeable_tensor = tf.Variable([10, 7])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [10]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [11]:
unchangeable_tensor = tf.constant([10, 7])
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [12]:
# creating random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape=(3, 2))
random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>)

In [13]:
tf.random.set_seed(42)
non_shuffled = tf.constant([[10, 7],
             [1, 2],
             [3, 5]])
shuffled = tf.random.shuffle(non_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  5],
       [10,  7]], dtype=int32)>

In [14]:
ones = tf.ones(shape=(2, 3))
ones

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [15]:
zeros = tf.zeros((1, 2))
zeros

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0., 0.]], dtype=float32)>

In [16]:
# X = tf.constant(some_matrix) -> uppercase
# y = tf.constant(some_vector) -> lowercase

Turn numpy array to tensorflow *tensor*

In [17]:
import numpy as np

np_array = np.arange(0, 10, dtype=np.int32)
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [18]:
a = tf.constant(np_array)
a

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [19]:
B = tf.constant(np_array, shape=(5, 2))
B

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]], dtype=int32)>

In [20]:
B = B.numpy()
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]], dtype=int32)

In [21]:
test = tf.random.uniform(shape=(2, 3, 4, 5))
test

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396],
         [0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256],
         [0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ],
         [0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ]],

        [[0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ],
         [0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ],
         [0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784],
         [0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097]],

        [[0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176],
         [0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
         [0.20301068, 0.11448455, 0.35100245, 0.68227184, 0.18108869],
         [0.8163481 , 0.65651655, 0.9258256 , 0.2391715 , 0.8365958 ]]],


       [[[0.04765272, 0.8007157 , 0.8299267 , 0.14328372, 0.8616878 ],
         [0.970

In [22]:
# Get the first 2 elements of each dimension
test[:2, :2, :2, :2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0.68789124, 0.48447883],
         [0.89256823, 0.94674826]],

        [[0.13803864, 0.12217975],
         [0.59708476, 0.6109482 ]]],


       [[[0.04765272, 0.8007157 ],
         [0.9707202 , 0.6779593 ]],

        [[0.14919603, 0.8594816 ],
         [0.70333743, 0.5343715 ]]]], dtype=float32)>

In [23]:
#get the first element from each index except the final one
test[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=
array([[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396]]]],
      dtype=float32)>

In [24]:
# tf.expand_dims
test.shape

TensorShape([2, 3, 4, 5])

In [25]:
tf.expand_dims(test, axis=-1).shape


TensorShape([2, 3, 4, 5, 1])

In [26]:
tensor1 = tf.random.uniform(shape=(3, 2), dtype=tf.dtypes.int32, maxval=5)
tensor2 = tf.random.uniform(shape=(2, 3), dtype=tf.dtypes.int32, maxval=5)
tensor1, tensor2

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[4, 2],
        [2, 4],
        [3, 2]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[4, 0, 4],
        [4, 2, 0]], dtype=int32)>)

In [27]:
tensor3 = tf.matmul(tensor1, tensor2)
tensor3

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[24,  4, 16],
       [24,  8,  8],
       [20,  4, 12]], dtype=int32)>

In [28]:
tensor3 = tensor1 @ tensor2
tensor3

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[24,  4, 16],
       [24,  8,  8],
       [20,  4, 12]], dtype=int32)>

In [29]:
tensor4 = tf.random.uniform(shape=(3, 2), dtype=tf.dtypes.int32, maxval=5)
tensor5 = tf.matmul(tensor3, tensor4)

In [30]:
tensor5 = tf.reshape(tensor5, shape=(2, 3))

In [31]:
tensor5 @ tensor4

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1236,  612],
       [ 720,  528]], dtype=int32)>

In [32]:
a = tf.constant([1, 2, 3, 4, 5, 6])

In [33]:
a = tf.reshape(a, shape=(2, 3))
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [34]:
tf.transpose(a, perm=[1, 0])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [35]:
tf.reshape(a, shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [36]:
# use tf.cast(a, dtype=tf.float16) to cast a to .dtype=tf.float16

In [37]:
# tf.abs()

In [38]:
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([39, 38, 63, 79, 60, 10, 86, 80, 12, 36, 82, 87, 84, 67,  6, 85, 36,
       38, 46, 39,  4, 30, 13, 58, 13, 70, 10, 65, 35, 26, 94, 42, 71, 31,
       36, 91, 96, 15, 30, 52, 34, 63,  3, 60, 56, 89, 45, 50,  0, 32])>

In [40]:
tf.reduce_min(E), tf.reduce_max(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=int64, numpy=96>)

In [41]:
tf.reduce_mean(E), tf.reduce_sum(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=47>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2387>)

In [42]:
import tensorflow_probability as tfp

tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=759>

In [47]:
tfp.stats.stddev(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.546186>

In [49]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=758.79236>

In [52]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [53]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [54]:
F[42]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [57]:
# squeeze
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [58]:
G.shape

TensorShape([1, 1, 1, 50])

In [60]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [61]:
# tf.squeeze() vs tf.expand_dims()

In [71]:
some_list = [1, 2, 3, 4]

tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [73]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [75]:
tf.constant(H.numpy())

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [76]:
np.array([1, 2, 3])

array([1, 2, 3])

In [77]:
# done, feel pretty good about working with basic tensors using tensorflow