<a href="https://colab.research.google.com/github/eric-sun92/tensorflow_tensor_fundamentals/blob/main/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim, scalar.shape

(0, TensorShape([]))

In [4]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[10, 7],
                      [7, 10]], dtype=tf.float16)
matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[10.,  7.],
        [ 7., 10.]], dtype=float16)>,
 2)

Changeable (tf.Variable) vs Non-changeable (tf.constant) Tensors

In [8]:
changeable_tensor = tf.Variable([10, 7])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [10]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [11]:
unchangeable_tensor = tf.constant([10, 7])
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [21]:
# creating random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape=(3, 2))
random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>)

In [52]:
tf.random.set_seed(42)
non_shuffled = tf.constant([[10, 7],
             [1, 2],
             [3, 5]])
shuffled = tf.random.shuffle(non_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  5],
       [10,  7]], dtype=int32)>

In [53]:
ones = tf.ones(shape=(2, 3))
ones

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [55]:
zeros = tf.zeros((1, 2))
zeros

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0., 0.]], dtype=float32)>

In [ ]:
# X = tf.constant(some_matrix) -> uppercase
# y = tf.constant(some_vector) -> lowercase

Turn numpy array to tensorflow *tensor*

In [62]:
import numpy as np

np_array = np.arange(0, 10, dtype=np.int32)
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [63]:
a = tf.constant(np_array)
a

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [65]:
B = tf.constant(np_array, shape=(5, 2))
B

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]], dtype=int32)>

In [66]:
B = B.numpy()
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]], dtype=int32)

In [83]:
test = tf.random.uniform(shape=(2, 3, 4, 5))
test

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0.803156  , 0.49777734, 0.37054038, 0.9118674 , 0.637642  ],
         [0.18209696, 0.63791955, 0.27701473, 0.04227114, 0.84219384],
         [0.90637195, 0.222556  , 0.9198462 , 0.68789077, 0.42705178],
         [0.878158  , 0.6943959 , 0.46567595, 0.52925766, 0.33019018]],

        [[0.12754858, 0.16153514, 0.5085137 , 0.44301772, 0.35205877],
         [0.8969147 , 0.24940813, 0.76328313, 0.85935795, 0.08480155],
         [0.20418596, 0.28848922, 0.65142167, 0.7106751 , 0.8695041 ],
         [0.23745108, 0.6688912 , 0.7115667 , 0.21899498, 0.7702793 ]],

        [[0.45055628, 0.95493364, 0.71695936, 0.98945487, 0.1511141 ],
         [0.06240606, 0.15209746, 0.99522185, 0.7830266 , 0.10455871],
         [0.40613055, 0.04687667, 0.83119476, 0.8572043 , 0.28471017],
         [0.2854122 , 0.3370154 , 0.6854944 , 0.46100128, 0.6476023 ]]],


       [[[0.65136576, 0.3152976 , 0.10924482, 0.05294752, 0.05602324],
         [0.113

In [84]:
# Get the first 2 elements of each dimension
test[:2, :2, :2, :2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0.803156  , 0.49777734],
         [0.18209696, 0.63791955]],

        [[0.12754858, 0.16153514],
         [0.8969147 , 0.24940813]]],


       [[[0.65136576, 0.3152976 ],
         [0.11310673, 0.26957738]],

        [[0.9031842 , 0.23433816],
         [0.5012578 , 0.9042305 ]]]], dtype=float32)>

In [85]:
#get the first element from each index except the final one
test[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=
array([[[[0.803156  , 0.49777734, 0.37054038, 0.9118674 , 0.637642  ]]]],
      dtype=float32)>

In [87]:
# tf.expand_dims
test.shape

TensorShape([2, 3, 4, 5])

In [90]:
tf.expand_dims(test, axis=-1).shape


TensorShape([2, 3, 4, 5, 1])

In [104]:
tensor1 = tf.random.uniform(shape=(3, 2), dtype=tf.dtypes.int32, maxval=5)
tensor2 = tf.random.uniform(shape=(2, 3), dtype=tf.dtypes.int32, maxval=5)
tensor1, tensor2

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 0],
        [4, 3],
        [4, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 0, 0],
        [4, 4, 2]], dtype=int32)>)

In [105]:
tensor3 = tf.matmul(tensor1, tensor2)
tensor3

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  0,  0],
       [16, 12,  6],
       [20, 16,  8]], dtype=int32)>

In [106]:
tensor3 = tensor1 @ tensor2
tensor3

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  0,  0],
       [16, 12,  6],
       [20, 16,  8]], dtype=int32)>

In [112]:
tensor4 = tf.random.uniform(shape=(3, 2), dtype=tf.dtypes.int32, maxval=5)
tensor5 = tf.matmul(tensor3, tensor4)

In [120]:
tensor5 = tf.reshape(tensor5, shape=(2, 3))

In [121]:
tensor5 @ tensor4

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 36, 184],
       [464, 808]], dtype=int32)>

In [137]:
a = tf.constant([1, 2, 3, 4, 5, 6])

In [138]:
a = tf.reshape(a, shape=(2, 3))
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [139]:
tf.transpose(a, perm=[1, 0])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [140]:
tf.reshape(a, shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [141]:
# use tf.cast(a, dtype=tf.float16) to cast a to .dtype=tf.float16